/* config.js — generated by the build. Public settings only: the Supabase anon key is designed to be public. */
window.APP_CONFIG = {
  "slug": "text-adventure-engine",
  "name": "Dungeon Narrator",
  "supabaseUrl": "",
  "supabaseAnonKey": "",
  "aiProxy": "",
  "google": false,
  "prompts": [
    {
      "say": "Start a new run as a cautious rogue",
      "does": "Creates the hero and begins the adventure."
    },
    {
      "say": "Search the room, then go north",
      "does": "Sends both moves to the game engine in order."
    },
    {
      "say": "Narrate everything like a noir detective story",
      "does": "Saves a standing style for the narrator."
    }
  ]
};
